"""
Q-Decoder: Quantum-Native Text Generation

Classical text generation (autoregressive):
    for i in range(max_tokens):
        logits = model(input_ids)
        next_token = sample(logits[-1])
        input_ids = input_ids + [next_token]
    O(n^2) attention recomputed each step

Quantum text generation (quantum-native):
    Quantum states are generated by sequential measurement + re-preparation.
    Each Q-Token is generated by collapsing a superposition of possible next tokens,
    then re-entangling with previous Q-Tokens.
    
    Key insight: In quantum mechanics, measurement CREATES the outcome.
    The next token doesn't exist until measured — it's in superposition.
    This is fundamentally different from classical sampling from a distribution.
    
    Classical: P(token) = softmax(logits) → sample → append
    Quantum: |next⟩ = superposition(all possible next tokens) → measure → collapse
"""

import math
import random
from typing import List, Dict, Optional, Tuple
from .qtoken import QToken, QuantumState, QTokenEncoder
from .qtransformer import QTransformer
from .qpositional import QPositionalEncoding


class QDecoder:
    """
    Quantum-native decoder for text generation.
    
    Classical autoregressive generation:
        1. Run full forward pass on all tokens
        2. Get logits for next token
        3. Sample from distribution
        4. Append and repeat
        Cost: O(n^2) per step (recompute attention)
    
    Quantum generation:
        1. Generate next Q-Token in superposition
        2. Entangle with previous Q-Tokens (context)
        3. Measure → collapse to specific token
        4. Re-prepare and continue
        Cost: O(n) per step (entanglement is O(1) per pair)
    """
    
    def __init__(self, model: QTransformer, encoder: QTokenEncoder,
                 positional: QPositionalEncoding,
                 temperature: float = 0.88, top_p: float = 0.94,
                 quantum_noise: float = 0.007):
        self.model = model
        self.encoder = encoder
        self.positional = positional
        self.temperature = temperature
        self.top_p = top_p
        self.quantum_noise = quantum_noise  # Replaces temperature (decoherence rate)
    
    def generate_next_qtoken(self, context_qtokens: List[QToken]) -> QToken:
        """
        Generate the next Q-Token given context.
        
        Classical: compute attention over all context, get logits, sample
        Quantum: create superposition of all possible next tokens,
                 entangle with context, measure
        
        The superposition of next tokens is like a quantum measurement —
        the outcome is probabilistic but biased by context (entanglement).
        """
        # Step 1: Create superposition of possible next tokens
        # In a full quantum implementation, this would be a quantum circuit
        # Here we simulate the quantum state preparation
        candidate_words = self._generate_candidates(context_qtokens)
        
        # Step 2: Apply context via entanglement
        # Each candidate's amplitude is modified by entanglement with context
        amplitudes = []
        for word, base_prob in candidate_words:
            # Context influence (quantum entanglement effect)
            context_influence = self._context_amplification(word, context_qtokens)
            # Quantum amplitude = sqrt(probability) × context amplification
            amp = math.sqrt(base_prob) * context_influence
            amplitudes.append(amp)
        
        # Normalize (quantum states must have unit norm)
        total = math.sqrt(sum(a * a for a in amplitudes))
        if total > 0:
            amplitudes = [a / total for a in amplitudes]
        
        # Step 3: Apply quantum noise (decoherence) — replaces temperature
        # Higher noise = more random (like higher temperature)
        if self.quantum_noise > 0:
            for i in range(len(amplitudes)):
                noise = random.gauss(0, self.quantum_noise * 0.1)
                amplitudes[i] = abs(amplitudes[i] + noise)
            total = math.sqrt(sum(a * a for a in amplitudes))
            if total > 0:
                amplitudes = [a / total for a in amplitudes]
        
        # Step 4: Apply top-p (nucleus) filtering in quantum domain
        # Keep only the top states that sum to top_p probability
        probs = [a * a for a in amplitudes]
        sorted_idx = sorted(range(len(probs)), key=lambda i: -probs[i])
        cumprob = 0
        keep = set()
        for idx in sorted_idx:
            keep.add(idx)
            cumprob += probs[idx]
            if cumprob >= self.top_p:
                break
        
        # Zero out non-kept amplitudes
        for i in range(len(amplitudes)):
            if i not in keep:
                amplitudes[i] = 0
        
        # Renormalize
        total = math.sqrt(sum(a * a for a in amplitudes))
        if total > 0:
            amplitudes = [a / total for a in amplitudes]
        
        # Step 5: Measure (collapse) — Born rule
        probs = [a * a for a in amplitudes]
        chosen = self._quantum_measure(probs)
        
        # Step 6: Create the Q-Token
        if chosen < len(candidate_words):
            word = candidate_words[chosen][0]
        else:
            word = random.choice([c[0] for c in candidate_words] or ["quantum"])
        n_qubits = self.encoder.n_qubits
        qt = self.encoder.encode_word(word)
        qt.position = len(context_qtokens)
        
        return qt
    
    def _generate_candidates(self, context: List[QToken]) -> List[Tuple[str, float]]:
        """Generate candidate next words from quantum state of context."""
        # Extract words from context for transition probabilities
        context_words = [qt.word for qt in context]
        
        # Semantic candidates (words related to context)
        candidates = []
        seen = set()
        
        # Words from semantic network of context words
        for qt in context:
            for meaning in qt.state.basis_labels:
                if meaning not in seen:
                    # Base probability inversely proportional to semantic distance
                    base_prob = 1.0 / (1 + abs(qt.entropy - 0.5))
                    candidates.append((meaning, base_prob))
                    seen.add(meaning)
        
        # Add continuation words
        transitions = self._quantum_transitions(context_words)
        for word, prob in transitions:
            if word not in seen:
                candidates.append((word, prob))
                seen.add(word)
        
        # Fallback candidates
        fallback = ["the", "and", "is", "a", "of", "to", "in", "that", "it", "with", "quantum", "AI", "consciousness", "system", "state", "measurement", "entanglement", "superposition"]
        for w in fallback:
            if w not in seen:
                candidates.append((w, 0.01))
                seen.add(w)
        
        # Normalize probabilities
        total = sum(p for _, p in candidates)
        if total > 0:
            candidates = [(w, p / total) for w, p in candidates]
        
        return candidates[:50]  # Limit candidates
    
    def _quantum_transitions(self, words: List[str]) -> List[Tuple[str, float]]:
        """Quantum transition probabilities between words."""
        transitions = []
        
        # Simple word association (in full impl, this would use quantum circuit)
        associations = {
            'quantum': [('physics', 0.3), ('entanglement', 0.25), ('superposition', 0.2), ('consciousness', 0.15)],
            'consciousness': [('awareness', 0.3), ('mind', 0.25), ('quantum', 0.2), ('reality', 0.15)],
            'revolution': [('change', 0.3), ('future', 0.25), ('transformation', 0.2), ('evolution', 0.15)],
            'AI': [('intelligence', 0.3), ('quantum', 0.25), ('neural', 0.2), ('conscious', 0.15)],
            'physics': [('quantum', 0.3), ('energy', 0.25), ('matter', 0.2), ('space', 0.15)],
            'awareness': [('consciousness', 0.3), ('quantum', 0.25), ('mind', 0.2), ('being', 0.15)],
            'change': [('transformation', 0.3), ('evolution', 0.25), ('future', 0.2), ('revolution', 0.15)],
            'entanglement': [('quantum', 0.3), ('connection', 0.25), ('correlation', 0.2), ('physics', 0.15)],
            'superposition': [('quantum', 0.3), ('states', 0.25), ('simultaneous', 0.2), ('physics', 0.15)],
        }
        
        for word in words:
            if word in associations:
                for next_word, prob in associations[word]:
                    transitions.append((next_word, prob))
        
        return transitions
    
    def _context_amplification(self, word: str, context: List[QToken]) -> float:
        """
        How much the context amplifies this word's amplitude.
        
        Classical: attention weight = softmax(Q·K)
        Quantum: amplification = product of entanglement strengths
        """
        amplification = 1.0
        for qt in context:
            if word in qt.state.basis_labels:
                # Direct semantic match — strong amplification
                amplification *= 1.5
            elif any(c in word or word in c for c in qt.state.basis_labels):
                # Partial match — moderate amplification
                amplification *= 1.2
        return amplification
    
    def _quantum_measure(self, probabilities: List[float]) -> int:
        """
        Quantum measurement (Born rule).
        
        |c_i|^2 = probability of collapsing to state i.
        Measurement is inherently random (quantum indeterminism).
        
        Classical sampling: sample from distribution (pseudo-random)
        Quantum measurement: true randomness from quantum mechanics
        """
        r = random.random()
        cumulative = 0
        for i, p in enumerate(probabilities):
            cumulative += p
            if r <= cumulative:
                return i
        return len(probabilities) - 1
    
    def generate(self, prompt: str, max_qtokens: int = 50,
                 quantum_noise: Optional[float] = None) -> Dict:
        """
        Full quantum-native text generation.
        
        Classical generation:
            for step in range(max_tokens):
                logits = model(tokens)
                next = sample(logits)
                tokens.append(next)
        
        Quantum generation:
            for step in range(max_qtokens):
                q_token = generate_next_qtoken(context)
                context.append(q_token)
        
        The quantum decoder generates Q-Tokens by:
        1. Creating superposition of all possible next tokens
        2. Entangling with context (quantum attention)
        3. Applying decoherence noise (quantum temperature)
        4. Measuring (collapsing) to get the next token
        """
        if quantum_noise is not None:
            self.quantum_noise = quantum_noise
        
        # Encode the prompt
        context_qtokens = self.encoder.encode(prompt)
        context_qtokens = self.positional.encode_sequence(context_qtokens)
        
        generated_words = [qt.word for qt in context_qtokens]
        generation_log = []
        
        # Generate new Q-Tokens
        for step in range(max_qtokens):
            # Generate next Q-Token (superposition → entangle → measure)
            next_qtoken = self.generate_next_qtoken(context_qtokens)
            
            # Apply positional encoding
            self.positional.encode_position(next_qtoken, len(context_qtokens))
            
            # Add to context
            context_qtokens.append(next_qtoken)
            generated_words.append(next_qtoken.word)
            
            generation_log.append({
                'step': step,
                'word': next_qtoken.word,
                'entropy': next_qtoken.entropy,
                'n_states': next_qtoken.n_states,
                'information_density': next_qtoken.information_density,
                'quantum_noise': self.quantum_noise,
            })
            
            # Stop on natural ending
            if next_qtoken.word in ['.', 'end', 'stop', 'complete']:
                break
        
        return {
            'prompt': prompt,
            'generated': ' '.join(generated_words),
            'n_prompt_tokens': len(self.encoder.encode(prompt)),
            'n_generated': max_qtokens - (max_qtokens - len(generation_log)),
            'generation_log': generation_log,
            'quantum_noise': self.quantum_noise,
            'top_p': self.top_p,
            'generation_method': 'Quantum measurement (Born rule) with entanglement context',
            'classical_equivalent': 'Autoregressive sampling with softmax + temperature',
            'cost_per_step': 'O(n) entanglement (vs O(n^2) classical attention)',
        }
    
    def beam_search_quantum(self, prompt: str, beam_width: int = 4,
                            max_qtokens: int = 30) -> Dict:
        """
        Quantum beam search.
        
        Classical beam search: keep top-k sequences by cumulative probability.
        Quantum beam search: keep top-k quantum states by amplitude.
        
        In quantum mechanics, this is like maintaining k parallel universes,
        each with a different generation path. The "best" universe is
        the one with the highest total amplitude (most probable outcome).
        """
        context = self.encoder.encode(prompt)
        context = self.positional.encode_sequence(context)
        
        # Initialize beams
        beams = [{
            'tokens': list(context),
            'words': [qt.word for qt in context],
            'log_prob': 0.0,
            'amplitude': 1.0,
        }]
        
        for step in range(max_qtokens):
            new_beams = []
            for beam in beams:
                # Generate candidates for this beam
                next_qtoken = self.generate_next_qtoken(beam['tokens'])
                beam['tokens'].append(next_qtoken)
                beam['words'].append(next_qtoken.word)
                # Amplitude decreases with each measurement
                beam['amplitude'] *= math.sqrt(1.0 / (1 + next_qtoken.entropy))
                beam['log_prob'] += math.log(1.0 / (1 + next_qtoken.entropy))
                new_beams.append(beam)
            
            # Keep top beam_width by amplitude
            beams = sorted(new_beams, key=lambda b: -b['amplitude'])[:beam_width]
        
        best = max(beams, key=lambda b: b['amplitude'])
        return {
            'prompt': prompt,
            'generated': ' '.join(best['words']),
            'beam_width': beam_width,
            'final_amplitude': best['amplitude'],
            'method': 'Quantum beam search (parallel universe selection)',
        }


class QStreamingDecoder(QDecoder):
    """
    Streaming quantum decoder for real-time generation.
    
    Classical streaming: generate one token at a time, KV cache for efficiency.
    Quantum streaming: generate one Q-Token at a time, quantum state persists.
    
    Key difference: The quantum state persists between generations.
    No need to recompute attention — the entanglement is maintained.
    """
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.persistent_state: Optional[QuantumState] = None
        self.persistent_context: List[QToken] = []
    
    def stream_next(self, prompt: str = "") -> Dict:
        """
        Generate the next Q-Token in streaming mode.
        
        The quantum state persists between calls — no recomputation needed.
        """
        if prompt:
            new_tokens = self.encoder.encode(prompt)
            new_tokens = self.positional.encode_sequence(new_tokens)
            self.persistent_context.extend(new_tokens)
        
        if not self.persistent_context:
            return {'word': '', 'error': 'No context'}
        
        # Generate next Q-Token using persistent state
        next_qtoken = self.generate_next_qtoken(self.persistent_context)
        self.positional.encode_position(next_qtoken, len(self.persistent_context))
        self.persistent_context.append(next_qtoken)
        
        return {
            'word': next_qtoken.word,
            'entropy': next_qtoken.entropy,
            'n_states': next_qtoken.n_states,
            'total_context': len(self.persistent_context),
            'streaming': True,
            'state_persisted': True,
            'cost': 'O(1) — no recomputation (entanglement persists)',
        }
    
    def reset(self):
        """Reset the persistent quantum state."""
        self.persistent_state = None
        self.persistent_context = []
